MACRO(NEW_EXECUTABLE EXECUTABLE_NAME EXE_FLAG)

    LINK_DIRECTORIES(${PATH_LIST})
    ADD_EXECUTABLE(${EXECUTABLE_NAME} ${EXECUTABLE_FILES})

    SET_TARGET_PROPERTIES(${EXECUTABLE_NAME} PROPERTIES DEBUG_POSTFIX "${CMAKE_DEBUG_POSTFIX}")
    SET_TARGET_PROPERTIES(${EXECUTABLE_NAME} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/lib"
                                                        ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/lib"
                                                        LIBRARY_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/lib"
                                                        LIBRARY_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/lib"
                                                        RUNTIME_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/bin"
                                                        RUNTIME_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/bin")

    TARGET_INCLUDE_DIRECTORIES(${EXECUTABLE_NAME} PUBLIC ${EXTERNAL_INCLUDES})
    TARGET_LINK_LIBRARIES(${EXECUTABLE_NAME} ${EXTERNAL_LIBRARIES})
    INSTALL(TARGETS ${EXECUTABLE_NAME} RUNTIME DESTINATION ${INSTALL_BINDIR}
                                        LIBRARY DESTINATION ${INSTALL_ARCHIVEDIR}
                                        ARCHIVE DESTINATION ${INSTALL_ARCHIVEDIR} OPTIONAL)

ENDMACRO(NEW_EXECUTABLE)

MACRO(NEW_CUDA_EXECUTABLE EXECUTABLE_NAME EXE_FLAG)

    LINK_DIRECTORIES(${PATH_LIST})
    IF(MUSA_FOUND)
        MUSA_ADD_EXECUTABLE(${EXECUTABLE_NAME} ${EXECUTABLE_FILES})
    ELSE()
        CUDA_ADD_EXECUTABLE(${EXECUTABLE_NAME} ${EXECUTABLE_FILES})
    ENDIF()

    SET_TARGET_PROPERTIES(${EXECUTABLE_NAME} PROPERTIES DEBUG_POSTFIX "${CMAKE_DEBUG_POSTFIX}")
    SET_TARGET_PROPERTIES(${EXECUTABLE_NAME} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/lib"
                                                        ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/lib"
                                                        LIBRARY_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/lib"
                                                        LIBRARY_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/lib"
                                                        RUNTIME_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/bin"
                                                        RUNTIME_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/bin")

    TARGET_INCLUDE_DIRECTORIES(${EXECUTABLE_NAME} PUBLIC ${EXTERNAL_INCLUDES})
    TARGET_LINK_LIBRARIES(${EXECUTABLE_NAME} ${EXTERNAL_LIBRARIES})
    INSTALL(TARGETS ${EXECUTABLE_NAME} RUNTIME DESTINATION ${INSTALL_BINDIR}
                                        LIBRARY DESTINATION ${INSTALL_ARCHIVEDIR}
                                        ARCHIVE DESTINATION ${INSTALL_ARCHIVEDIR} OPTIONAL)

ENDMACRO(NEW_CUDA_EXECUTABLE)

MACRO(NEW_LIBRARY LIBRARY_NAME LIBRARY_TYPE)

    LINK_DIRECTORIES(${PATH_LIST})
    ADD_LIBRARY(${LIBRARY_NAME} ${LIBRARY_TYPE} ${LIBRARY_FILES})

    SET_TARGET_PROPERTIES(${LIBRARY_NAME} PROPERTIES DEBUG_POSTFIX "${CMAKE_DEBUG_POSTFIX}")
    SET_TARGET_PROPERTIES(${LIBRARY_NAME} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/lib"
                                                     ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/lib"
                                                     LIBRARY_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/lib"
                                                     LIBRARY_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/lib"
                                                     RUNTIME_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/bin"
                                                     RUNTIME_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/bin")

    TARGET_INCLUDE_DIRECTORIES(${LIBRARY_NAME} PUBLIC ${EXTERNAL_INCLUDES})
    TARGET_LINK_LIBRARIES(${LIBRARY_NAME} ${EXTERNAL_LIBRARIES})
    INSTALL(TARGETS ${LIBRARY_NAME} RUNTIME DESTINATION ${INSTALL_BINDIR}
                                    LIBRARY DESTINATION ${INSTALL_ARCHIVEDIR}
                                    ARCHIVE DESTINATION ${INSTALL_ARCHIVEDIR} OPTIONAL)

ENDMACRO(NEW_LIBRARY)

MACRO(NEW_CUDA_LIBRARY LIBRARY_NAME LIBRARY_TYPE)

    LINK_DIRECTORIES(${PATH_LIST})
    IF(MUSA_FOUND)
        MUSA_ADD_LIBRARY(${LIBRARY_NAME} ${LIBRARY_TYPE} ${LIBRARY_FILES})
    ELSE()
        CUDA_ADD_LIBRARY(${LIBRARY_NAME} ${LIBRARY_TYPE} ${LIBRARY_FILES})
    ENDIF()

    SET_TARGET_PROPERTIES(${LIBRARY_NAME} PROPERTIES DEBUG_POSTFIX "${CMAKE_DEBUG_POSTFIX}")
    SET_TARGET_PROPERTIES(${LIBRARY_NAME} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/lib"
                                                     ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/lib"
                                                     LIBRARY_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/lib"
                                                     LIBRARY_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/lib"
                                                     RUNTIME_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/bin"
                                                     RUNTIME_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/bin")

    TARGET_INCLUDE_DIRECTORIES(${LIBRARY_NAME} PUBLIC ${EXTERNAL_INCLUDES})
    TARGET_LINK_LIBRARIES(${LIBRARY_NAME} ${EXTERNAL_LIBRARIES})
    INSTALL(TARGETS ${LIBRARY_NAME} RUNTIME DESTINATION ${INSTALL_BINDIR}
                                    LIBRARY DESTINATION ${INSTALL_ARCHIVEDIR}
                                    ARCHIVE DESTINATION ${INSTALL_ARCHIVEDIR} OPTIONAL)

ENDMACRO(NEW_CUDA_LIBRARY)

MACRO(NEW_PLUGIN LIBRARY_NAME LIBRARY_TYPE)

    LINK_DIRECTORIES(${PATH_LIST})
    ADD_LIBRARY(${LIBRARY_NAME} ${LIBRARY_TYPE} ${LIBRARY_FILES})

    SET_TARGET_PROPERTIES(${LIBRARY_NAME} PROPERTIES DEBUG_POSTFIX "${CMAKE_DEBUG_POSTFIX}")
    SET_TARGET_PROPERTIES(${LIBRARY_NAME} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/lib"
                                                     ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/lib"
                                                     LIBRARY_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/lib"
                                                     LIBRARY_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/lib"
                                                     RUNTIME_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/bin"
                                                     RUNTIME_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/bin")

    TARGET_INCLUDE_DIRECTORIES(${LIBRARY_NAME} PUBLIC ${EXTERNAL_INCLUDES})
    TARGET_LINK_LIBRARIES(${LIBRARY_NAME} ${EXTERNAL_LIBRARIES})

ENDMACRO(NEW_PLUGIN)

MACRO(NEW_CUDA_PLUGIN LIBRARY_NAME LIBRARY_TYPE)

    LINK_DIRECTORIES(${PATH_LIST})
    IF(MUSA_FOUND)
        MUSA_ADD_LIBRARY(${LIBRARY_NAME} ${LIBRARY_TYPE} ${LIBRARY_FILES})
    ELSE()
        CUDA_ADD_LIBRARY(${LIBRARY_NAME} ${LIBRARY_TYPE} ${LIBRARY_FILES})
    ENDIF()

    SET_TARGET_PROPERTIES(${LIBRARY_NAME} PROPERTIES DEBUG_POSTFIX "${CMAKE_DEBUG_POSTFIX}")
    SET_TARGET_PROPERTIES(${LIBRARY_NAME} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/lib"
                                                     ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/lib"
                                                     LIBRARY_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/lib"
                                                     LIBRARY_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/lib"
                                                     RUNTIME_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/bin"
                                                     RUNTIME_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/bin")

    TARGET_INCLUDE_DIRECTORIES(${LIBRARY_NAME} PUBLIC ${EXTERNAL_INCLUDES})
    TARGET_LINK_LIBRARIES(${LIBRARY_NAME} ${EXTERNAL_LIBRARIES})

ENDMACRO(NEW_CUDA_PLUGIN)

MACRO(FIND_DEPENDENCE_EX DEP_NAME INCLUDE_NAMES LIB_NAMES INC_PATH_POSTFIX BE_QUITE)

    SET(${DEP_NAME}_FOUND FALSE)
    SET(${DEP_NAME}_FEATURE_ENABLED ON CACHE BOOL "Enable to search for ${DEP_NAME} dependencies")
    IF(${DEP_NAME}_FEATURE_ENABLED)
        SET(USR_SEARCH_PATH /usr)
        IF(USE_WASM_OPTIONS OR ANDROID)
            SET(USR_SEARCH_PATH ${THIRDPARTY_ROOT})
        ENDIF()

        IF(NOT "${INC_PATH_POSTFIX}" STREQUAL "")
            LIST(LENGTH INC_PATH_POSTFIX INC_LIST_LENGTH)
            IF(INC_LIST_LENGTH EQUAL 0)
                FIND_PATH(${DEP_NAME}_INCLUDE_DIR ${INCLUDE_NAMES}
                    PATHS ${THIRDPARTY_ROOT}/include/${INC_PATH_POSTFIX}
                    ${USR_SEARCH_PATH}/include/${INC_PATH_POSTFIX}
                    ${USR_SEARCH_PATH}/local/include/${INC_PATH_POSTFIX}
                    NO_CMAKE_FIND_ROOT_PATH
                )
            ELSE(INC_LIST_LENGTH EQUAL 0)
                SET(${DEP_NAME}_INCLUDE_DIR "")
                FOREACH(INC_ITEM IN LISTS INC_PATH_POSTFIX)
                    FIND_PATH(TEMP_RESULT ${INCLUDE_NAMES}
                        PATHS ${THIRDPARTY_ROOT}/include/${INC_ITEM}
                        ${USR_SEARCH_PATH}/include/${INC_ITEM}
                        ${USR_SEARCH_PATH}/local/include/${INC_ITEM}
                        NO_CMAKE_FIND_ROOT_PATH
                    )

                    IF(TEMP_RESULT)
                        SET(${DEP_NAME}_INCLUDE_DIR ${TEMP_RESULT})
                        UNSET(TEMP_RESULT CACHE)
                        BREAK()
                    ENDIF()
                    UNSET(TEMP_RESULT CACHE)
                ENDFOREACH()
            ENDIF(INC_LIST_LENGTH EQUAL 0)
        ELSE()
            FIND_PATH(${DEP_NAME}_INCLUDE_DIR ${INCLUDE_NAMES}
                PATHS ${THIRDPARTY_ROOT}/include
                ${USR_SEARCH_PATH}/include ${USR_SEARCH_PATH}/local/include
                NO_CMAKE_FIND_ROOT_PATH
            )
        ENDIF()

        IF(NOT "${LIB_NAMES}" STREQUAL "")
            FIND_PATH(${DEP_NAME}_LIB_DIR ${LIB_NAMES}
                PATHS ${THIRDPARTY_ROOT}/lib ${USR_SEARCH_PATH}/lib
                ${USR_SEARCH_PATH}/${FIND_LIB_POSTFIX} ${USR_SEARCH_PATH}/lib/${FIND_SUBLIB_POSTFIX}
                ${USR_SEARCH_PATH}/local/lib ${USR_SEARCH_PATH}/local/${FIND_LIB_POSTFIX}
                NO_CMAKE_FIND_ROOT_PATH
            )

            IF(${DEP_NAME}_INCLUDE_DIR AND ${DEP_NAME}_LIB_DIR)
                # Don't add *_INCLUDE_DIR here, to avoid too many confusingly global include paths
                # But we have to add *_LINK_DIR so to ensure we can always find dependencies of libraries
                LINK_DIRECTORIES(${${DEP_NAME}_LIB_DIR})
                SET(${DEP_NAME}_FOUND TRUE)
            ELSE(${DEP_NAME}_INCLUDE_DIR AND ${DEP_NAME}_LIB_DIR)
                IF(NOT ${BE_QUITE})
                    MESSAGE("[osgVerse] Dependency ${DEP_NAME} not found. Some functionalities will be ignored.")
                ENDIF()
            ENDIF(${DEP_NAME}_INCLUDE_DIR AND ${DEP_NAME}_LIB_DIR)
        ELSE()
            IF(${DEP_NAME}_INCLUDE_DIR)
                SET(${DEP_NAME}_FOUND TRUE)
            ELSE(${DEP_NAME}_INCLUDE_DIR)
                IF(NOT ${BE_QUITE})
                    MESSAGE("[osgVerse] Dependency ${DEP_NAME} not found. Some functionalities will be ignored.")
                ENDIF()
            ENDIF(${DEP_NAME}_INCLUDE_DIR)
        ENDIF()
    ENDIF(${DEP_NAME}_FEATURE_ENABLED)

    IF(${DEP_NAME}_FOUND)
        SET_PROPERTY(GLOBAL APPEND PROPERTY VERSE_DEPENDENCIES "${DEP_NAME}")
    ENDIF()

ENDMACRO(FIND_DEPENDENCE_EX)

MACRO(FIND_DEPENDENCE DEP_NAME INCLUDE_NAMES LIB_NAMES INC_PATH_POSTFIX)

    FIND_DEPENDENCE_EX("${DEP_NAME}" "${INCLUDE_NAMES}" "${LIB_NAMES}" "${INC_PATH_POSTFIX}" FALSE)

ENDMACRO(FIND_DEPENDENCE)

MACRO(USE_MSVC_DEBUGGER EXECUTABLE_NAME PATH_ENV)

    IF(MSVC)
        SET_TARGET_PROPERTIES(${EXECUTABLE_NAME} PROPERTIES VS_DEBUGGER_WORKING_DIRECTORY "${CMAKE_INSTALL_PREFIX}/bin")
        IF("${CMAKE_VERSION}" VERSION_GREATER 3.12)
            STRING(REPLACE "\\" "/" SAFE_PATH_ENV "${PATH_ENV}")
            SET_TARGET_PROPERTIES(${EXECUTABLE_NAME} PROPERTIES VS_DEBUGGER_ENVIRONMENT "PATH=${SAFE_PATH_ENV}")
        ENDIF()
    ENDIF(MSVC)

ENDMACRO(USE_MSVC_DEBUGGER)

MACRO(USE_STATIC_RUNTIME)

    IF(MSVC)
        FOREACH(FLAG_VAR
                CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG CMAKE_CXX_FLAGS_RELEASE
                CMAKE_CXX_FLAGS_MINSIZEREL CMAKE_CXX_FLAGS_RELWITHDEBINFO)
            IF(${FLAG_VAR} MATCHES "/MD")
                STRING(REGEX REPLACE "/MD" "/MT" ${FLAG_VAR} "${${FLAG_VAR}}")
            ENDIF(${FLAG_VAR} MATCHES "/MD")
        ENDFOREACH(FLAG_VAR)
    ENDIF(MSVC)

ENDMACRO(USE_STATIC_RUNTIME)
